[tool.poetry]
name = "fitness"
version = "0.1.0"
description = "Analysis of my fitness data"
authors = ["Ethan Swan <eswan18@rocketmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.0"
altair = "^5.0"
seaborn = "^0.12.0"
streamlit = "^1.24.1"
watchdog = "^4.0.0"

[tool.poetry.dev-dependencies]
jupyterlab = "^3.5.0"
black = "^22.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
